# External Incentives I

## Research funders

::: {.callout-note icon=false}
### &#127465;&#127466; DFG

*DFG Guidelines on the Handling of Research Data*

> "Assuming that the publication of research data [...] does not conflict with the rights of third parties (in particular data protection or copyright), research data should be *made available* as soon as possible [...] that allows it to be usefully *reused* by third parties" [@DFG.2015b, p. 1]  
  
*Guidelines for Safeguarding Good Research Practice. Code of Conduct*

> "Where possible and reasonable, this includes making the research data [...] available" [@DFG.2019a, p. 19]
:::

\

::: {.callout-important icon=false}
### &#127468;&#127463; ESRC

*ESRC research data policy*  
  
> "Publicly-funded research data are a public good, produced in the public interest, which shall be made openly available and accessible with as few restrictions as possible" [@ESRC.2018, p. 2]


:::

\

::: {.callout-tip icon=false}
### &#127482;&#127480; NSF

*Proposal & Award Policies & Procedures Guide*    
    
You will need to hand in...

> "plans for archiving data, samples, and other research products, and for preservation of access to them" [@NSF.2023, p. II-32]


:::



\

::: {.callout-caution icon=false}
### &#127466;&#127482; ERC 
*Open Research Data and Data Management Plans Information for ERC grantees*

> "Grantees are required to deposit their research data in a repository and provide open access at least to those data"
[@ERC.2022, p. 4]
:::

::: {.column-margin}
Questions to be answered at the end?  
Please [put them here](https://cryptpad.fr/pad/#/2/pad/edit/cuCPFUjVKcURc7JZSKt57dK2/embed/)!
:::