# Workflow 3

```{r}
```


## Informed consent
**Why?**  

* *Personal data* is subject to General Data Protection Regulation (GDPR)
* Informed consent must therefore fulfill a number of requirements. E.g.,
  - purpose of data collection (includes *sharing the data* and *future use*)<br />`r fontawesome::fa("right-long", height="1em", width="1em")` therefore often "broad consent"
  - participation is voluntary and without disadvantages
  - revocation is possible at any time (until anonymized)
   
**Resources**  

* &#127482;&#127480; [Recommendations of ICPSR](https://www.icpsr.umich.edu/web/pages/datamanagement/confidentiality/conf-language.html)
* &#127468;&#127463; [Information, samples and model forms of UK Data Service](https://ukdataservice.ac.uk/learning-hub/research-data-management/ethical-issues/consent-for-data-sharing/)
* &#127465;&#127466; [Information, samples and model forms of VerbundFDB](https://www.forschungsdaten-bildung.de/handreichungen)
* &#127475;&#127473; [Good overview with Dos and Don'ts, University of Utrecht](https://www.uu.nl/en/research/research-data-management/guides/legal-considerations/how-to-write-an-informed-consent-form)
* [Overview + links (ZPID), English](https://datawizkb.leibniz-psychology.org/index.php/before-my-project-starts/informed-consent/)
* [Explanations + definitions (Michigan Tech), US](https://www.mtu.edu/research/integrity/docs/michigan-tech-hrpp-standard-operations-procedures.pdf)
* [Checklist, German](https://doi.org/10.25656/01:22297)
* [Template, German standard language](https://doi.org/10.25656/01:22301)
* [Template, German plain language](https://doi.org/10.25656/01:22302)
* [Template (qualitative data), German](https://www.qualiservice.org/de/datenschutz.html)
* [Explanations + template (DGPs), German](https://zwpd.transmit.de/images/zwpd/dienstleistungen/ethikkommission/0.1a_datenschutzrechtliche_empfehlungen_einwilligungforschungsvorhaben.pdf)

\

## Decide for access restrictions
**Why?**  

* Some data *cannot or should not be anonymized* (e.g., losing their reuse potential)
   - Therefore access needs to be restricted to certain groups (as defined in consent form)
* Some researchers fear being *scooped* [@Laine.2017]

::: {.callout-note collapse="true" icon=false}
### With repositories...
restriction levels are usually limited to

* public (everybody sees everything)
* private (only you and your collaborators see everything)
:::

::: {.callout-note collapse="true" icon=false}
### With research data centers... 
there are different restriction levels possible for different files (*in the same project*). Restriction levels depend on what the research data center offers.   
\
  
| Level              | Prerequesite                                                                                             | For what                                                         |   |
|--------------------|----------------------------------------------------------------------------------------------------------|------------------------------------------------------------------|---|
| Public Usefile     |                                                                                                          | anonymized data, codebooks, transcription rules                  |   |
| Student Usefile    | Short application states use purpose                                                                     | non-anonymized data with right to use for teaching               |   |
| Scientific Usefile | Longer application states use purpose, handling of data, and data analyses; identification via PostIdent | non-anonymized data with right to use for research               |   |
| Remote Access      | ... + access only via virtual machine                                                                    | non-anonymized sensible data with right to use for research      |   |
| Safe room          | ... + access only in person at research institute                                                        | non-anonymized very sensible data with right to use for research |   |
  
\

An example: [Project DESI](http://dx.doi.org/10.7477/6:1:1), where 

* codebooks are publicly accessible (files on the right side)
* video data are restricted for scientific use (files on the bottom of page)

:::

   

**Alternatives to restricting**  

* *Embargo period*
  - Specify a time period, before data go public
  - Possible with research data centers and some repositories
* *Exclude certain research questions* from reuse
  - Specify these research questions in the terms of use
  - Usually only possible with research data centers, except you are writing a very good license yourself
* Create *synthetic data* (e.g., with R package [`synthpop`](https://synthpop.org.uk/))
  - Mimics the properties of your data
  - Then possible to share this synthetic data set

::: {.column-margin}
Questions to be answered at the end?  
Please [put them here](https://cryptpad.fr/pad/#/2/pad/edit/cuCPFUjVKcURc7JZSKt57dK2/embed/)!
:::

\
